### ISSUE TITLE
Problem with bat file to build Webkit.Interop.dll

### ISSUE THREAD

**Issue by Jennal** [webkitdotnet/webkitdotnet#1]
The bat file to build Webkit.Interop.dll uses the default framework version to build Webkit.Interop.dll

This is not good for who uses vs2010 like me, the framework version is 4.0, then WebKitBrowser can't be build successfully.

We need to build Webkit.Interop.dll on vs2008, then remove the pre-build scripts on vs2010. This is not good.

Hope you could fix this issue, thanks:)

**Comment by alensiljak** [comment]
I had to change batch file to be able to run from VS Command Prompt:

set SolutionDir=C:\Hg\Lib\webkitdotnet\
set ProjectDir=%SolutionDir%

call "%DevEnvDir%....\VC\vcvarsall.bat" x86
if not exist "%SolutionDir%tools\TypeNormalizer.exe" csc /out:"%SolutionDir%tools\TypeNormalizer.exe" "%SolutionDir%tools\TypeNormalizer.cs"
tlbimp "%SolutionDir%webkit\webkit.tlb" /silent /keyfile:"%ProjectDir%WebKit .NET.snk" /namespace:WebKit.Interop /out:"%SolutionDir%webkit\WebKit.Interop.dll"
ildasm "%SolutionDir%webkit\WebKit.Interop.dll" /out="%SolutionDir%webkit\temp_webkit_interop.il" /nobar
"%SolutionDir%tools\TypeNormalizer.exe" "%SolutionDir%webkit\temp_webkit_interop.il"
ilasm "%SolutionDir%webkit\temp_webkit_interop.il" /dll /output="%SolutionDir%webkit\WebKit.Interop.dll" /key="%ProjectDir%WebKit.NET.snk"
del /F /Q "%SolutionDir%webkit\temp_webkit_interop.*"
