### ISSUE TITLE
SSL is not supported?

### ISSUE THREAD

**Issue by turutosiya** [webkitdotnet/webkitdotnet#11]
webkitdotnet do not navigate the url which starts with "https://～"
Will it be fixed?

**Comment by therealmitchconnors** [comment]
What error is the application giving you?  Are you capturing the Error event of the Browser?  What https site are you trying to navigate to?  I may have a few suggestions, but I need more details.

**Comment by turutosiya** [comment]
The Error event was raised by WebKitBrowser control. the error contains the description below : 
"Problem with the SSL CA cert (path? access rights?)"

**Comment by therealmitchconnors** [comment]
hmmm... that is not an error I have seen.  It sounds like you may need to grab a new cert file, as Sam mentioned at https://sourceforge.net/projects/webkitdotnet/forums/forum/939856/topic/3345480 .  You need to make sure that you have the .pem file, and that the process executing WebKit has access rights to the .pem file for at least read.  But not having experienced that error, it's hard to say.
