### ISSUE TITLE
Printer settings not set on PrintDocument

### ISSUE THREAD

**Issue by petersondrew** [webkitdotnet/webkitdotnet#17]
I've found a bug with document printing in webkitdotnet. The PrintDocument.PageSetings are copied to the new document, those contain PrinterSettings, but those settings are never assigned to the PrintDocument.PrinterSettings object.
I'm not sure how you prefer patches to be submitted, and I've never done a pull request on github before, but I can give you the diff:

```diff --git a/WebKitCore/WebKitBrowserCore.cs b/WebKitCore/WebKitBrowserCore.cs
index 4fbe65f..5a86cf2 100644
--- a/WebKitCore/WebKitBrowserCore.cs
+++ b/WebKitCore/WebKitBrowserCore.cs
@@ -1058,6 +1058,7 @@ namespace WebKit
             doc.DocumentName = this.DocumentTitle;
             doc.DefaultPageSettings = PageSettings;
             doc.OriginAtMargins = true;
-            doc.PrinterSettings = PageSettings.PrinterSettings;^M
           return doc;
       }

```
```

**Comment by petersondrew** [comment]
Without the patch, documents always print with the default printer settings.

**Comment by peterdn** [comment]
Added to develop branch
