### ISSUE TITLE
Cookies are not working, no apparent way to allow them?

### ISSUE THREAD

**Issue by adamkdean** [webkitdotnet/webkitdotnet#28]
Visiting http://stackoverflow.com/network-login-help/ shows that cookies are not working.

Not sure if there is a more up to date version of this project but at this point I'm thinking this project is pretty much _dead in the water_.

Am I right?

**Comment by peterdn** [comment]
This is an issue with WinCairo WebKit.  I've submitted a bug report and patch (https://bugs.webkit.org/show_bug.cgi?id=110147) which will hopefully be accepted soon.  I'll keep this issue open until then.  In the meanwhile, I will commit a fixed build of WebKit to the develop branch.

**Comment by peterdn** [comment]
This has now been fixed in WebKit 

http://trac.webkit.org/changeset/143272
http://trac.webkit.org/changeset/144853
