### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by jrpbuilds** [webkitdotnet/webkitdotnet#5]
Hi there, Was just wondering if there was a reason why the WebURLRequest parameter needs to be done manually and not pushed to master? Does it affect builds under VS 2008 or something?

Thanks!

**Comment by antwankakki** [comment]
use https://github.com/webkitdotnet/webkitdotnet/wiki/_pages to help you building
use http://webkitdotnet.sourceforge.net/docs/  for API reference
welcome to webkitdotnet community, for a specific answer for your question wait couple days and u'll get one :) hope i helped

**Comment by jrpbuilds** [comment]
Yeah got it to build was just wondering if it could be committed or as I suspect it will cause conflicts :)

Thanks for the reply though!

**Comment by antwankakki** [comment]
You are welcome :)

**Comment by antwankakki** [comment]
oh and don't thank me thank TestSubjectRC2 for the tutorials

**Comment by jrpbuilds** [comment]
Thanks for clarifing, I suspected so.  Sorry I must admit I didn't check for other branches!

Thanks for the responce!
