### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by crossiron** [webkitdotnet/webkitdotnet#7]
I don't know if this only hapens to me, but the webkit test does not download is it not developed yet or is it an error of mine?

**Comment by antwankakki** [comment]
what do u mean by it doesn't download here is a direct link https://download.github.com/webkitdotnet-webkitdotnet-160a223.zip

**Comment by crossiron** [comment]
I'm sorry, i made myself unclear. What i meant was in the WK.net Test solution, downloading a file does not work

**Comment by crossiron** [comment]
I'm sorry, I didn't read that, thank you for the information. Is there an ETA for the nex release?

**Comment by antwankakki** [comment]
so does the downloads work or what?

**Comment by crossiron** [comment]
No it does not
